// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/diplomatic-atlas/OperationsAtlas.tsx": () => import("../components/mockups/diplomatic-atlas/OperationsAtlas.tsx"),
  "./components/mockups/diplomatic-homepage/EditorialRefined.tsx": () => import("../components/mockups/diplomatic-homepage/EditorialRefined.tsx"),
  "./components/mockups/diplomatic-homepage/Homepage.tsx": () => import("../components/mockups/diplomatic-homepage/Homepage.tsx"),
  "./components/mockups/diplomatic-homepage/HomepageMobile.tsx": () => import("../components/mockups/diplomatic-homepage/HomepageMobile.tsx"),
  "./components/mockups/diplomatic-homepage/TerracottaLedger.tsx": () => import("../components/mockups/diplomatic-homepage/TerracottaLedger.tsx")
};
